"""add hide_from_reports to transactions

Revision ID: 588da15b2e4d
Revises: 7c528cb149ab
Create Date: 2026-03-30 16:44:33.558994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588da15b2e4d'
down_revision: Union[str, Sequence[str], None] = '7c528cb149ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('hide_from_reports', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'hide_from_reports')
    # ### end Alembic commands ###
