"""add_fire_engine_tables

Revision ID: 824eb0c8c847
Revises: f017f6721aeb
Create Date: 2026-03-14 22:41:32.364955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '824eb0c8c847'
down_revision: Union[str, Sequence[str], None] = 'f017f6721aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fire_config',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('target_retirement_age', sa.Integer(), nullable=True),
    sa.Column('target_retirement_date', sa.Date(), nullable=True),
    sa.Column('life_expectancy', sa.Integer(), nullable=False),
    sa.Column('fire_variant', sa.String(), nullable=False),
    sa.Column('safe_withdrawal_rate', sa.Float(), nullable=False),
    sa.Column('expected_annual_return', sa.Float(), nullable=False),
    sa.Column('expected_inflation_rate', sa.Float(), nullable=False),
    sa.Column('target_annual_spending', sa.BigInteger(), nullable=True),
    sa.Column('social_security_monthly', sa.BigInteger(), nullable=True),
    sa.Column('social_security_start_age', sa.Integer(), nullable=False),
    sa.Column('pension_monthly', sa.BigInteger(), nullable=True),
    sa.Column('pension_start_age', sa.Integer(), nullable=True),
    sa.Column('healthcare_monthly_cost', sa.BigInteger(), nullable=True),
    sa.Column('medicare_start_age', sa.Integer(), nullable=False),
    sa.Column('rmd_start_age', sa.Integer(), nullable=False),
    sa.Column('state_tax_rate', sa.Float(), nullable=True),
    sa.Column('federal_marginal_rate', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('goal_type', sa.Enum('NET_WORTH_TARGET', 'SAVINGS_RATE_TARGET', 'EXPENSE_REDUCTION', 'DEBT_PAYOFF', 'INCOME_TARGET', 'RETIREMENT_DATE', 'CUSTOM', name='goal_type'), nullable=False),
    sa.Column('target_value', sa.BigInteger(), nullable=True),
    sa.Column('target_percentage', sa.Float(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('current_value', sa.BigInteger(), nullable=True),
    sa.Column('current_percentage', sa.Float(), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ACHIEVED', 'MISSED', 'CANCELLED', name='goal_status'), nullable=False),
    sa.Column('metric_query', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income_sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('income_type', sa.Enum('SALARY', 'BONUS', 'RENTAL', 'DIVIDEND', 'SIDE_HUSTLE', 'SOCIAL_SECURITY', 'PENSION', 'OTHER', name='income_type'), nullable=False),
    sa.Column('annual_amount', sa.BigInteger(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('is_taxable', sa.Boolean(), nullable=False),
    sa.Column('tax_treatment', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('linked_account_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('income_sources')
    op.drop_table('goals')
    op.drop_table('fire_config')
    # ### end Alembic commands ###
