"""add_target_legacy_to_fire_config

Revision ID: 89955ab596c0
Revises: 824eb0c8c847
Create Date: 2026-03-14 23:02:57.987179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89955ab596c0'
down_revision: Union[str, Sequence[str], None] = '824eb0c8c847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fire_config', sa.Column('target_legacy', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fire_config', 'target_legacy')
    # ### end Alembic commands ###
