"""add_asset_hub_tables_and_account_enrichment

Revision ID: f017f6721aeb
Revises: a4c43b4694fe
Create Date: 2026-03-14 21:50:42.526237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f017f6721aeb'
down_revision: Union[str, Sequence[str], None] = 'a4c43b4694fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physical_assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_category', sa.Enum('REAL_ESTATE', 'VEHICLE', 'PRIVATE_INVESTMENT', name='asset_category'), nullable=False),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchase_price', sa.BigInteger(), nullable=True),
    sa.Column('current_value', sa.BigInteger(), nullable=False),
    sa.Column('valuation_method', sa.String(), nullable=True),
    sa.Column('last_valued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('linked_account_id', sa.UUID(), nullable=True),
    sa.Column('external_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_tracking_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fire_role', sa.String(), nullable=True),
    sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aspirations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_cost', sa.BigInteger(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Enum('MUST_HAVE', 'NICE_TO_HAVE', 'DREAM', name='aspiration_priority'), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('linked_asset_id', sa.UUID(), nullable=True),
    sa.Column('funding_source', sa.String(), nullable=True),
    sa.Column('financing_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ongoing_cost_delta', sa.BigInteger(), nullable=True),
    sa.Column('fire_impact_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'APPROVED', 'PURCHASED', 'CANCELLED', name='aspiration_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_asset_id'], ['physical_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_valuations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['physical_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'date', name='uq_asset_valuation_asset_date')
    )
    op.add_column('accounts', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('accounts', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('accounts', sa.Column('fire_role', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('target_balance', sa.BigInteger(), nullable=True))
    op.add_column('accounts', sa.Column('target_allocation_pct', sa.Float(), nullable=True))
    op.add_column('accounts', sa.Column('strategy', sa.Text(), nullable=True))
    op.add_column('accounts', sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'custom_data')
    op.drop_column('accounts', 'strategy')
    op.drop_column('accounts', 'target_allocation_pct')
    op.drop_column('accounts', 'target_balance')
    op.drop_column('accounts', 'fire_role')
    op.drop_column('accounts', 'tags')
    op.drop_column('accounts', 'notes')
    op.drop_table('asset_valuations')
    op.drop_table('aspirations')
    op.drop_table('physical_assets')
    # ### end Alembic commands ###
